"""Update server files permissions

Revision ID: b10d9ed82b8f
Revises: a5ea65ee5ef9
Create Date: 2026-08-26 23:12:32.812229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b10d9ed82b8f'
down_revision: Union[str, Sequence[str], None] = 'a5ea65ee5ef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE permissionenum ADD VALUE IF NOT EXISTS 'SERVER_FILES_CREATE'")
    op.execute("ALTER TYPE permissionenum ADD VALUE IF NOT EXISTS 'SERVER_FILES_DELETE'")
    op.execute("ALTER TYPE permissionenum ADD VALUE IF NOT EXISTS 'SERVER_FILES_UPLOAD'")
    op.execute("ALTER TYPE permissionenum ADD VALUE IF NOT EXISTS 'SERVER_FILES_EXTRACT'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
